name: deploy
on:
  push:
    branches:
      - master
jobs:
  deploy-to-docker-hub:
    runs-on: ubuntu-latest
    env:
      DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
      DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
      DOCKER_HUB_REPO: ${{ secrets.DOCKER_HUB_REPO }}
    steps:
      - uses: actions/checkout@v2
      - run: bash ./infrastructure/ci.sh
